package co.psyke.nanosoftma.models;

public enum DoctorType {
	ALLERGIST,
	ANAESTHETICS,
	CARDIOLOGY,
	DERMATOLOGY,
	ENDOCRINOLOGY,
	GENERAL,
	GASTROENTEROLOGY,
	GERIATRICS,
	HEMATOLOGY,
	IMMUNOLOGY,
	INFECTIOUS_DISEASES,
	INTERNAL_MEDICINE,
	NEPHROLOGY,
	NEUROPSYCHIATRY,
	NEUROLOGY,
	NEUROSURGERY,
	GYNAECOLOGY,
	ONCOLOGY,
	OPHTHALMOLOGY,
	ORTHOPAEDICS,
	OTORHINOLARYNGOLOGY,
	PAEDIATRIC,
	PATHOLOGY,
	PHARMACOLOGY,
	PSYCHIATRY,
	NONE;

	public static boolean present(String s) {
		for(DoctorType type : values()){
			if(type.toString().equals(s)) 
				return true; 
		}	
		return false; 
	}
}
